[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

; T-Display-S3 配置
build_flags = 
    -DBOARD_HAS_PSRAM
    -DBOARD_MODEL=\"ESP32-S3\"

; WiFi OTA 上传 (首次需要USB,之后可用这个)
; upload_protocol = espota
; upload_port = 192.168.1.xxx
